name = "example_sdl_app"
version = "0.1.0"
defaultTargets = ["ExampleSDLApp"]

[leanOptions]
autoImplicit = false

[[require]]
name = "sdl_bindings"
path = "../sdl-bindings"

[[lean_lib]]
name = "ExampleSDLApp"
srcDir = "lean"
roots = ["ExampleSDL"]
defaultFacets = ["static"]
